version: "3.7"

services:
  db:
    image: postgres:12-alpine
    container_name: dvdrental-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dvdrental
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - sb-pg-net
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb/:/docker-entrypoint-initdb.d/
      - ./dvdrental.tar:/home/data/dvdrental.tar
  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pager-hazelcast-demo-api-1
    ports:
      - "8081:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "JAVA_OPTS=-DhazelCastNodes=hazelcast:5701"
    networks:
      - sb-pg-net
    depends_on:
      db:
        condition: service_healthy
      hazelcast:
        condition: service_started
  app2:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pager-hazelcast-demo-api-2
    ports:
      - "8082:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "JAVA_OPTS=-DhazelCastNodes=hazelcast:5701"
    networks:
      - sb-pg-net
    depends_on:
      db:
        condition: service_healthy
      hazelcast:
        condition: service_started
  hazelcast:
    hostname: hazelcast
    image: hazelcast/hazelcast:${HAZELCAST_VERSION:-5.3.0-slim}
    ports:
      - "5701:5701"
    networks:
      - sb-pg-net
  management-center:
    image: hazelcast/management-center:${HAZELCAST_VERSION:-5.3.0}
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast:5701
      - MC_ALLOW_MULTIPLE_LOGIN=true
      - MC_ADMIN_USER=admin
      - MC_ADMIN_PASSWORD=b4bJ56*F
    ports:
      - "8080:8080"
    depends_on:
      hazelcast:
        condition: service_started
    networks:
      - sb-pg-net
networks:
  sb-pg-net:
    driver: bridge

volumes:
  db-data: