version: "3.7"

services:
  db:
    image: postgres:12-alpine
    container_name: dvdrental-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dvdrental
    networks:
      - sb-pg-net
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb/:/docker-entrypoint-initdb.d/
      - ./dvdrental.tar:/home/data/dvdrental.tar
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pager-demo-api
    ports:
      - "8080:8080"
    networks:
      - sb-pg-net
    depends_on:
      - db

networks:
  sb-pg-net:
    driver: bridge

volumes:
  db-data: