version: "3.9"

services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    container_name: db-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - sb-pg-net
    volumes:
      - db-data:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION:-7.2.1}
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-logs:/var/lib/zookeeper/log
    networks:
      - sb-pg-net
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.2.1}
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9999:9999"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 29092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - sb-pg-net
    volumes:
      - kafka-data:/var/lib/kafka/data
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    hostname: kafka-manager
    container_name: kafka-manager
    depends_on:
      - kafka
      - zookeeper
    command: -Dconfig.file=/kafka-manager/conf/application.conf -Dapplication.home=/kafkamanager
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: randomSecret
    networks:
      - sb-pg-net
    ports:
      - "9000:9000"
  manager-cluster-init:
    image: ellerbrock/alpine-bash-curl-ssl
    restart: "no"
    container_name: init
    environment:
      KAFKA_MANAGER_HOST: kafka-manager:9000
      KAFKA_CLUSTER_NAME: ${KAFKA_CLUSTER_NAME:-testing}
      KAFKA_VERSION: ${KAFKA_VERSION:-2.4.0}
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka-manager
      - kafka
      - zookeeper
    networks:
      - sb-pg-net
    command: /bin/bash /kafka-cluster-init.sh
    volumes:
      - "./kafka/kafka-cluster-init.sh:/kafka-cluster-init.sh"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-batch-examples
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://db-server:5432/springbatchdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - API_PORT=8080
      - KAFKA_BROKER=kafka:29092
    networks:
      - sb-pg-net
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
networks:
  sb-pg-net:
    driver: bridge

volumes:
  db-data:
  zk-data:
  zk-logs:
  kafka-data: